#!/usr/bin/env python3
"""
Test PDF export functionality in minimal environment
"""

import sys
import os
import tempfile
import subprocess
from pathlib import Path

# Add src to path
src_path = Path.cwd() / "src"
if src_path.exists() and str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

def test_pdf_export():
    """Test that PDF export functionality works with ghostscript"""
    try:
        print("Testing PDF export functionality...")
        
        # Create a simple PostScript file
        ps_content = """%!PS-Adobe-3.0
%%BoundingBox: 0 0 612 792
%%Title: Test PostScript File
%%Creator: Microwell GUI Test
%%EndComments

/Times-Roman findfont
12 scalefont
setfont

100 700 moveto
(This is a test PostScript file for PDF conversion) show

100 680 moveto
(Generated by Microwell Plate GUI test suite) show

showpage
%%EOF"""
        
        # Create temporary files
        with tempfile.NamedTemporaryFile(mode='w', suffix='.ps', delete=False) as ps_file:
            ps_file.write(ps_content)
            ps_path = ps_file.name
        
        pdf_path = ps_path.replace('.ps', '.pdf')
        
        try:
            # Test ps2pdf conversion
            print(f"Converting {ps_path} to {pdf_path}")
            result = subprocess.run(['ps2pdf', ps_path, pdf_path], 
                                  capture_output=True, text=True, timeout=30)
            
            if result.returncode == 0:
                print("✅ ps2pdf conversion successful")
                
                # Check if PDF was created
                if os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 0:
                    print(f"✅ PDF file created: {pdf_path} ({os.path.getsize(pdf_path)} bytes)")
                    
                    # Clean up
                    os.unlink(ps_path)
                    os.unlink(pdf_path)
                    print("✅ Cleanup successful")
                    
                    return True
                else:
                    print("❌ PDF file not created or empty")
                    return False
            else:
                print(f"❌ ps2pdf failed: {result.stderr}")
                return False
                
        except subprocess.TimeoutExpired:
            print("❌ ps2pdf conversion timed out")
            return False
        except Exception as e:
            print(f"❌ ps2pdf conversion error: {e}")
            return False
        finally:
            # Clean up files if they exist
            for file_path in [ps_path, pdf_path]:
                if os.path.exists(file_path):
                    try:
                        os.unlink(file_path)
                    except:
                        pass
                        
    except Exception as e:
        print(f"❌ PDF export test failed: {e}")
        return False

def test_ghostscript_commands():
    """Test that both gs and ps2pdf commands are available"""
    print("Testing Ghostscript commands...")
    
    # Test gs command
    try:
        result = subprocess.run(['gs', '--version'], 
                              capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            print(f"✅ gs command available: version {result.stdout.strip()}")
            gs_ok = True
        else:
            print("❌ gs command failed")
            gs_ok = False
    except Exception as e:
        print(f"❌ gs command error: {e}")
        gs_ok = False
    
    # Test ps2pdf command (it doesn't have --version, so test with no args)
    try:
        result = subprocess.run(['ps2pdf'], 
                              capture_output=True, text=True, timeout=10)
        # ps2pdf returns error code when no args, but that means it's available
        if "Usage:" in result.stderr or result.returncode == 1:
            print("✅ ps2pdf command available")
            ps2pdf_ok = True
        else:
            print("❌ ps2pdf command not working properly")
            ps2pdf_ok = False
    except Exception as e:
        print(f"❌ ps2pdf command error: {e}")
        ps2pdf_ok = False
    
    return gs_ok and ps2pdf_ok

if __name__ == "__main__":
    print("🧬 PDF Export Functionality Test")
    print("=" * 40)
    
    # Test commands first
    commands_ok = test_ghostscript_commands()
    
    if commands_ok:
        # Test actual PDF conversion
        pdf_ok = test_pdf_export()
        success = pdf_ok
    else:
        success = False
    
    print("\n" + "=" * 40)
    print(f"PDF Export Test: {'PASSED' if success else 'FAILED'}")
    
    if success:
        print("✅ PDF export functionality is working correctly")
        print("✅ Ghostscript integration is functional")
    else:
        print("❌ PDF export functionality has issues")
        print("❌ Check ghostscript installation")
    
    sys.exit(0 if success else 1)